### ISSUE TITLE
Allow specifying ingress annotations 

### ISSUE THREAD

**Issue by cfarrend** [kubevious/deploy#2]
Hey,

Really like this tool so far, it has been much more useful than we originally thought.

We are thinking to put it behind an ingress, however the annotations cannot be specified. In our example we are going to use `external-dns.alpha.kubernetes.io/hostname` 

Not sure where we can make a PR as the charts are in a versioned folder already, but some examples are here:
https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-ingress.yaml#L15
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-ingress.yaml#L15
https://github.com/sstarcher/helm-exporter/blob/master/helm/templates/ingress.yaml#L14

Also correct me if I'm wrong but `networking.gke.io/managed-certificates: kubevious-certificate` in `ingress.yaml` might conflict for people who aren't using such a certificate?

**Comment by rubenhak** [comment]
Thanks for the hint on annotations. That's quite useful. Will include that in the next version. For now it would be probably best for you to set **.Values.ingress.enabled=false** and configure the Ingress manually so you don't get blocked on this.

You also made me realize that Ingress yaml is specific to GKE and wouldn't work in other environments. Need to find solution to that.

The **kubevious-certificate** is deployed along with the Ingress. See here: [https://github.com/kubevious/deploy/blob/master/kubernetes/kubevious/templates/ingress.yaml#L4-L13](https://github.com/kubevious/deploy/blob/master/kubernetes/kubevious/templates/ingress.yaml#L4-L13). But that only works in GKE.

**Comment by rubenhak** [comment]
@cfarrend,  would you be able to take a look to the following helm values table? This is not final, so please don't use the charts yet. 
[https://github.com/kubevious/helm#helm-chart-values](https://github.com/kubevious/helm#helm-chart-values)

**Comment by kubevious** [comment]
@cfarrend, the issue with ingress is resolved. Please refer to helm chart and its configuration here: [https://github.com/kubevious/helm](https://github.com/kubevious/helm).

For any further requests, please submit and issue to the root repo: [https://github.com/kubevious/kubevious](https://github.com/kubevious/kubevious)

Thank you!
